after_script:
  - rake yard | tee yard.out
  - grep --silent '100.00% documented' yard.out
before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - rake db:setup
language: ruby
rvm:
  - '1.9.3'
  - 'jruby-19mode'
