before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - bundle exec rake db:setup
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-1.7.17
sudo: false
